// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-TKc46rmM9cIv0nOrII2Y0bsVgZOLTaU',
    appId: '1:593918829944:web:aa8e260fcb0af8aade948d',
    messagingSenderId: '593918829944',
    projectId: 'test-chat-app-1dde8',
    authDomain: 'test-chat-app-1dde8.firebaseapp.com',
    storageBucket: 'test-chat-app-1dde8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJTv576TMBYv_t53qlG5lSVW076CMcuaw',
    appId: '1:593918829944:android:c4f5e941261c4580de948d',
    messagingSenderId: '593918829944',
    projectId: 'test-chat-app-1dde8',
    storageBucket: 'test-chat-app-1dde8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCp5mfeBkLqK1URdYtUFjfl3-d-UqBrjc',
    appId: '1:593918829944:ios:df484d6b460e857ede948d',
    messagingSenderId: '593918829944',
    projectId: 'test-chat-app-1dde8',
    storageBucket: 'test-chat-app-1dde8.appspot.com',
    iosClientId: '593918829944-qqullpdtg016hikkpq9rn1d68s0bjaeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
